[package]
name = "helix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
owo-colors = "4.0.0"
thiserror = "1.0.57"
